version: '3'

services:
  youbetcha-loyalty-service-ci:
    image: youbetcha/youbetcha-loyalty-service:latest
    container_name: youbetcha-loyalty-service-ci
    restart: unless-stopped
    volumes:
      - /tmp/app/logs:/logs
    environment:
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "spring.profiles.active=ci"
      - "LOGS_FILENAME=loyalty-service-logger-ci"
      - "SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:9093"
    ports:
      - 17610:17610

networks:
  default:
    external:
      name: ci

