version: '3'

services:
  youbetcha-loyalty-service-prod:
    image: internal-api.youbetcha.com:5000/youbetcha-loyalty-service:${APP_VERSION}
    container_name: youbetcha-loyalty-service-prod
    restart: unless-stopped
    volumes:
      - /tmp/app/logs:/logs
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://db-prod.youbetcha.com:3306/loyaltydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      - "SPRING_DATASOURCE_USERNAME=loyalty_service"
      - "SPRING_DATASOURCE_PASSWORD=loyalty2login"
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "spring.profiles.active=prod"
      - "LOGS_FILENAME=loyalty-service-logger-prod"
    ports:
      - 17611:17611

networks:
  default:
    external:
      name: prod