version: '3'

services:
  db:
    restart: always
    container_name: mariadb
    image: mariadb:10.5
    ports:
      - "13306:13306"
    environment:
      MYSQL_DATABASE: paymentsdb
      MYSQL_USER: payments_service
      MYSQL_PASSWORD: payments2login
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
networks:
  default:
    external:
      name: staging
