server:
  port: 17700
  servlet:
    context-path: /payments-service
  jetty:
    acceptors: 50 # Number of acceptor threads to use.
    max-http-post-size: 100000 # Maximum size in bytes of the HTTP post or put content.
    selectors: 50 # Number of selector threads to use.
    idle-timeout: 120

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
        hibernate:
            show_sql: true
            format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

service:
  host: localhost

internal:
  player-service:
    host-name: localhost
    port: 17500
    context: player-service

everymatrix:
  merchant:
    id: 2207
    key: FF6669994ACE4B3993985F85DB0F5ED6
  server-api:
    host-name: https://core-gm-stage.everymatrix.com
    version: 1.0
    partner-id: 2207YoubetchaSiteID
    partner-key: K54vNGEk94g9AgTQ
  casino-engine:
    host-name: http://casino.everymatrix.com
    operator-key: key
  game-launch:
    host-name: https://gamelaunch.everymatrix.com/Loader/Start
    domain-id: 1
  money-matrix:
    host-name: https://api-stage.moneymatrix.com/api/v1/Hosted
    callback-url: https://api-stg.youbetcha.com/payments-service/external-api/v1/payments/init/transaction/status/change
    check-status-url: https://api-stg.youbetcha.com/payments-service/external-api/v1/payments/init/transaction/status/check

management:
  info:
    git:
      mode: full