version: '3'

services:
  youbetcha-notification-service-staging:
    image: docker.youbetcha.com:5000/youbetcha-notification-service:${APP_VERSION}
    container_name: youbetcha-notification-service-staging
    restart: unless-stopped
    volumes:
      - /opt/app/youbetcha/youbetcha-notification-service/logs:/logs
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://db-test.youbetcha.com:3306/notificationdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      - "SPRING_DATASOURCE_USERNAME=notification_service"
      - "SPRING_DATASOURCE_PASSWORD=notification2login"
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "spring.profiles.active=staging"
      - "LOGS_FILENAME=player-notification-service-logger-staging"
      - "SPRING_KAFKA_BOOTSTRAPSERVERS=internal-api-stg.youbetcha.com:9092"
    ports:
      - 17901:17901

networks:
  default:
    external:
      name: staging