server:
  port: 17611
  servlet:
    context-path: /loyalty-service
  jetty:
    acceptors: 50 # Number of acceptor threads to use.
    max-http-post-size: 100000 # Maximum size in bytes of the HTTP post or put content.
    selectors: 50 # Number of selector threads to use.
    connection-idle-timeout: 60000

spring:
  application:
    name: youbetcha-loyalty-service-prod
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mariadb://db-prod.youbetcha.com:3306/loyaltydb
    driverClassName: org.mariadb.jdbc.Driver
    username: loyalty_service
    password: loyalty2login
    jpa:
      database-platform: org.hibernate.dialect.MariaDB103Dialect

everymatrix:
  acs:
    host-name: https://acs-external-stage.everymatrix.com
    username: youbetcha_appuser
    password: V_6a}NY<!?)yE4r=
  ubs:
    host-name: http://ubs.stage.everymatrix.com/
  server-api:
    host-name: https://core-gm-stage.everymatrix.com
    version: 1.0
    partner-id: 2207YoubetchaSiteID
    partner-key: K54vNGEk94g9AgTQ
  casino-engine:
    host-name: http://casino2.stage.everymatrix.com
    operator-key: youbetcha_com
  game-launch:
    host-name: https://gamelaunch-stage.everymatrix.com/Loader/Start
    domain-id: 2207

kafka:
  broker: "kafka:9093"
  topic: registration-prod
  consumer-group: consumerGroupProd

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO


