version: '3'

services:
  youbetcha-payments-service-prod:
    image: docker.youbetcha.com:5000/youbetcha-payments-service:${APP_VERSION}
    container_name: youbetcha-payments-service-prod
    restart: unless-stopped
    expose:
      - "5678"
    volumes:
      - /opt/app/youbetcha/youbetcha-payments-service/logs:/logs
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://db-prod.youbetcha.com:3306/paymentsdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      - "SPRING_DATASOURCE_USERNAME=payments_service"
      - "SPRING_DATASOURCE_PASSWORD=payments2login"
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "spring.profiles.active=prod"
      - "LOGS_FILENAME=payments-service-logger-prod"
      - "SPRING_KAFKA_BOOTSTRAPSERVERS=internal-api.youbetcha.com:9092"
    ports:
      - 17702:17702

networks:
  default:
    external:
      name: prod

