version: '3'

services:
  youbetcha-player-service-prod:
    image: docker.youbetcha.com:5000/youbetcha-player-service:${APP_VERSION}
    container_name: youbetcha-player-service-prod
    restart: unless-stopped
    expose:
      - "5678"
    volumes:
      - /opt/app/youbetcha/youbetcha-player-service/logs:/logs
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://db-prod.youbetcha.com:3306/playerdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      - "SPRING_DATASOURCE_USERNAME=player_service"
      - "SPRING_DATASOURCE_PASSWORD=player2login"
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "SPRING_PROFILES_ACTIVE=prod"
      - "spring.profiles.active=prod"
      - "LOGS_FILENAME=player-service-logger-prod"
      - "SPRING_KAFKA_BOOTSTRAPSERVERS=internal-api.youbetcha.com:9092"
    ports:
      - 17502:17502

networks:
  default:
    external:
      name: prod