version: '3'

services:
  youbetcha-loyalty-service-staging:
    image: localhost:5000/youbetcha-loyalty-service:${APP_VERSION}
    container_name: youbetcha-loyalty-service-staging
    restart: unless-stopped
    volumes:
      - /tmp/app/logs:/logs
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://95.217.114.223:3306/loyaltydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      - "SPRING_DATASOURCE_USERNAME=loyalty_service"
      - "SPRING_DATASOURCE_PASSWORD=loyalty2login"
      - "JAVA_OPTS=-Xmx256m -Xms128m"
      - "spring.profiles.active=staging"
      - "LOGS_FILENAME=loyalty-service-logger-staging"
    ports:
      - 17611:17611
networks:
  default:
    external:
      name: ci