package com.youbetcha.model.payments;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
public enum TransactionStage {
	
	DEPOSIT_INITIAL_REQUEST,
	DEPOSIT_LIMIT_REQUEST,
	DEPOSIT_CASHIER_REQUEST,
	DEPOSIT_CASHIER_OUTCOME,
	DEPOSIT_STATUS_CHECK,
	DEPOSIT_STATUS_CHANGE,
	DEPOSIT_GM_INITIAL_REQUEST,
	DEPOSIT_GM_REQUEST,
	DEPOSIT_GM_RESPONSE,
	WITHDRAW_INITIAL_REQUEST,
	WITHDRAW_GM_REQUEST,
	WITHDRAW_CASHIER_REQUEST,
	WITHDRAW_CASHIER_OUTCOME,
	WITHDRAW_STATUS_CHECK,
	WITHDRAW_GM_INITIAL_REQUEST,
	WITHDRAW_STATUS_CHANGE,
	WITHDRAW_GM_PROCEED_REQUEST,
	WITHDRAW_GM_PROCEED_RESPONSE,
	WITHDRAW_GM_ROLLBACK_REQUEST,
	WITHDRAW_GM_ROLLBACK_RESPONSE;
	
    @Setter
	@Getter
    private String value;
}
