server:
  port: 17501
  servlet:
    context-path: /player-service
  jetty:
    acceptors: 50 # Number of acceptor threads to use.
    max-http-post-size: 100000 # Maximum size in bytes of the HTTP post or put content.
    selectors: 50 # Number of selector threads to use.
    connection-idle-timeout: 60000

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: internal-api-stg.youbetcha.com
          defaultBrokerPort: 9092
  application:
    name: youbetcha-player-service-staging
  datasource:
    url: jdbc:mariadb://internal-api-stg.youbetcha.com:3306/playerdb
    driverClassName: org.mariadb.jdbc.Driver
    username: player_service
    password: player2login
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect

service:
  host: https://beta-stg.youbetcha.com

everymatrix:
  merchant:
    id: 2207
    key: FF6669994ACE4B3993985F85DB0F5ED6
  server-api:
    host-name: https://core-gm-stage.everymatrix.com
    version: 1.0
    partner-id: 2207YoubetchaSiteID
    partner-key: K54vNGEk94g9AgTQ
  casino-engine:
    host-name: http://casino2.stage.everymatrix.com
    operator-key: youbetcha_com
  game-launch:
    host-name: https://gamelaunch-stage.everymatrix.com/Loader/Start
    domain-id: 2207

management:
  endpoint:
    health:
      show-details: always


